<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PatientsSeeder extends Seeder
{
    public function run()
    {
        // Insert into patients table
        DB::table('patients')->insert([
            // Students
            ['patient_id' => 1, 'type' => 'student', 'lname' => 'Dela Cruz', 'fname' => 'Juan', 'mname' => 'M', 'ext' => NULL, 'birthdate' => '2003-05-10', 'gender' => 1, 'civil_status' => NULL, 'email' => 'juan.delacruz@uni.ph', 'mobile' => '09171234567', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['patient_id' => 2, 'type' => 'student', 'lname' => 'Santos', 'fname' => 'Maria', 'mname' => 'L', 'ext' => NULL, 'birthdate' => '2004-07-15', 'gender' => 0, 'civil_status' => NULL, 'email' => 'maria.santos@uni.ph', 'mobile' => '09181234568', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['patient_id' => 3, 'type' => 'student', 'lname' => 'Reyes', 'fname' => 'Carlos', 'mname' => 'B', 'ext' => NULL, 'birthdate' => '2002-12-20', 'gender' => 0, 'civil_status' => NULL, 'email' => 'carlos.reyes@uni.ph', 'mobile' => '09191234569', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['patient_id' => 4, 'type' => 'student', 'lname' => 'Gonzales', 'fname' => 'Ana', 'mname' => 'C', 'ext' => NULL, 'birthdate' => '2003-09-05', 'gender' => 0, 'civil_status' => NULL, 'email' => 'ana.gonzales@uni.ph', 'mobile' => '09201234570', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['patient_id' => 5, 'type' => 'student', 'lname' => 'Torres', 'fname' => 'Miguel', 'mname' => 'D', 'ext' => NULL, 'birthdate' => '2004-11-25', 'gender' => 0, 'civil_status' => NULL, 'email' => 'miguel.torres@uni.ph', 'mobile' => '09211234571', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],

            // Employees
            ['patient_id' => 6, 'type' => 'employee', 'lname' => 'Fernandez', 'fname' => 'Luis', 'mname' => 'E', 'ext' => NULL, 'birthdate' => '1985-06-22', 'gender' => 1, 'civil_status' => 1, 'email' => 'luis.fernandez@uni.ph', 'mobile' => '09221234572', 'telephone' => '0498765432', 'created_at' => now(), 'updated_at' => now()],
            ['patient_id' => 7, 'type' => 'employee', 'lname' => 'Cruz', 'fname' => 'Jessica', 'mname' => 'F', 'ext' => NULL, 'birthdate' => '1990-04-18', 'gender' => 0, 'civil_status' => 1, 'email' => 'jessica.cruz@uni.ph', 'mobile' => '09231234573', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['patient_id' => 8, 'type' => 'employee', 'lname' => 'Ramos', 'fname' => 'Adrian', 'mname' => 'G', 'ext' => NULL, 'birthdate' => '1982-10-30', 'gender' => 1, 'civil_status' => 1, 'email' => 'adrian.ramos@uni.ph', 'mobile' => '09241234574', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['patient_id' => 9, 'type' => 'employee', 'lname' => 'Aguilar', 'fname' => 'Samantha', 'mname' => 'H', 'ext' => NULL, 'birthdate' => '1995-08-12', 'gender' => 0, 'civil_status' => 1, 'email' => 'samantha.aguilar@uni.ph', 'mobile' => '09251234575', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['patient_id' => 10, 'type' => 'employee', 'lname' => 'Lopez', 'fname' => 'Daniel', 'mname' => 'I', 'ext' => NULL, 'birthdate' => '1987-03-07', 'gender' => 1, 'civil_status' => 1, 'email' => 'daniel.lopez@uni.ph', 'mobile' => '09261234576', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],

            // Non-Personnel
            ['patient_id' => 11, 'type' => 'non_personnel', 'lname' => 'Villanueva', 'fname' => 'Arnel', 'mname' => 'J', 'ext' => NULL, 'birthdate' => '1978-02-14', 'gender' => 1, 'civil_status' => 1, 'email' => 'arnel.villanueva@uni.ph', 'mobile' => '09271234577', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['patient_id' => 12, 'type' => 'non_personnel', 'lname' => 'Marquez', 'fname' => 'Cynthia', 'mname' => 'K', 'ext' => NULL, 'birthdate' => '1980-09-28', 'gender' => 0, 'civil_status' => 1, 'email' => 'cynthia.marquez@uni.ph', 'mobile' => '09281234578', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['patient_id' => 13, 'type' => 'non_personnel', 'lname' => 'Salazar', 'fname' => 'Roberto', 'mname' => 'L', 'ext' => NULL, 'birthdate' => '1975-06-05', 'gender' => 1, 'civil_status' => 1, 'email' => 'roberto.salazar@uni.ph', 'mobile' => '09291234579', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['patient_id' => 14, 'type' => 'non_personnel', 'lname' => 'Medina', 'fname' => 'Angela', 'mname' => 'M', 'ext' => NULL, 'birthdate' => '1983-12-10', 'gender' => 0, 'civil_status' => 1, 'email' => 'angela.medina@uni.ph', 'mobile' => '09301234580', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['patient_id' => 15, 'type' => 'non_personnel', 'lname' => 'Navarro', 'fname' => 'Felipe', 'mname' => 'N', 'ext' => NULL, 'birthdate' => '1992-07-19', 'gender' => 1, 'civil_status' => 1, 'email' => 'felipe.navarro@uni.ph', 'mobile' => '09311234581', 'telephone' => NULL, 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('students')->insert([
            ['stud_id' => '2023001', 'patient_id' => 1, 'is_vaccinated' => 1, 'father_name' => 'Jose Dela Cruz', 'father_birthdate' => '1970-03-15', 'father_occupation' => 'Engineer', 'mother_name' => 'Maria Dela Cruz', 'mother_birthdate' => '1975-06-25', 'mother_occupation' => 'Teacher', 'guardian_name' => 'Pedro Dela Cruz', 'guardian_relation' => 'Uncle', 'guardian_contactno' => '09179876543', 'address_house' => 'Blk 1 Lot 2', 'address_brgy' => 'Poblacion', 'address_citytown' => 'Los Baños', 'address_province' => 'Laguna', 'address_zipcode' => 4030, 'emergency_contact_name' => 'Pedro Dela Cruz', 'emergency_contact_no' => '09179876543', 'college_id' => 6, 'program_id' => 12, 'created_at' => now(), 'updated_at' => now()], 
            ['stud_id' => '2023002', 'patient_id' => 2, 'is_vaccinated' => 1, 'father_name' => 'Juan Santos', 'father_birthdate' => '1972-01-10', 'father_occupation' => 'Mechanic', 'mother_name' => 'Luisa Santos', 'mother_birthdate' => '1976-02-14', 'mother_occupation' => 'Nurse', 'guardian_name' => 'Ana Santos', 'guardian_relation' => 'Aunt', 'guardian_contactno' => '09171234560', 'address_house' => '123 St.', 'address_brgy' => 'San Pedro', 'address_citytown' => 'San Pablo', 'address_province' => 'Laguna', 'address_zipcode' => 4023, 'emergency_contact_name' => 'Ana Santos', 'emergency_contact_no' => '09171234560', 'college_id' => 10, 'program_id' => 2, 'created_at' => now(), 'updated_at' => now()], 
            ['stud_id' => '2023003', 'patient_id' => 3, 'is_vaccinated' => 0, 'father_name' => 'Miguel Reyes', 'father_birthdate' => '1968-09-25', 'father_occupation' => 'Farmer', 'mother_name' => 'Clara Reyes', 'mother_birthdate' => '1970-11-30', 'mother_occupation' => 'Housewife', 'guardian_name' => 'Juan Reyes', 'guardian_relation' => 'Grandfather', 'guardian_contactno' => '09175678910', 'address_house' => '456 Ave.', 'address_brgy' => 'Calamba', 'address_citytown' => 'Calamba', 'address_province' => 'Laguna', 'address_zipcode' => 4027, 'emergency_contact_name' => 'Juan Reyes', 'emergency_contact_no' => '09175678910', 'college_id' => 10, 'program_id' => 4, 'created_at' => now(), 'updated_at' => now()], 
            ['stud_id' => '2023004', 'patient_id' => 4, 'is_vaccinated' => 1, 'father_name' => 'Carlos Gonzales', 'father_birthdate' => '1980-06-08', 'father_occupation' => 'Policeman', 'mother_name' => 'Susan Gonzales', 'mother_birthdate' => '1983-03-19', 'mother_occupation' => 'Doctor', 'guardian_name' => 'Maria Gonzales', 'guardian_relation' => 'Sister', 'guardian_contactno' => '09172345678', 'address_house' => '789 Road', 'address_brgy' => 'Batangas City', 'address_citytown' => 'Batangas', 'address_province' => 'Batangas', 'address_zipcode' => 4200, 'emergency_contact_name' => 'Maria Gonzales', 'emergency_contact_no' => '09172345678', 'college_id' => 11, 'program_id' => 6, 'created_at' => now(), 'updated_at' => now()], 
            ['stud_id' => '2023005', 'patient_id' => 5, 'is_vaccinated' => 1, 'father_name' => 'Antonio Torres', 'father_birthdate' => '1975-12-01', 'father_occupation' => 'Chef', 'mother_name' => 'Teresa Torres', 'mother_birthdate' => '1978-10-23', 'mother_occupation' => 'Teacher', 'guardian_name' => 'Jose Torres', 'guardian_relation' => 'Uncle', 'guardian_contactno' => '09173456789', 'address_house' => '101 St.', 'address_brgy' => 'Santa Rosa', 'address_citytown' => 'Santa Rosa', 'address_province' => 'Laguna', 'address_zipcode' => 4026, 'emergency_contact_name' => 'Jose Torres', 'emergency_contact_no' => '09173456789', 'college_id' => 13, 'program_id' => 8, 'created_at' => now(), 'updated_at' => now()]
        ]);        

        DB::table('employees')->insert([
            ['p_id' => 1, 'patient_id' => 6, 'employee_no' => 'EMP001', 'date_hired' => '2010-05-15', 'is_active' => 1, 'height' => 5.8, 'weight' => 160, 'blood_type' => 'O+', 'father_name' => 'Rodolfo Fernandez', 'mother_name' => 'Lilia Fernandez', 'spouse_name' => 'Maricel Fernandez', 'spouse_occupation' => 'Accountant', 'emergency_contact_person' => 'Anna Fernandez', 'emergency_contact_number' => '09228765432', 'res_brgy' => 'Brgy 1', 'res_city' => 'Los Baños', 'res_prov' => 'Laguna', 'res_region' => 4, 'res_zipcode' => '4030', 'dept_id' => 14, 'college_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['p_id' => 2, 'patient_id' => 7, 'employee_no' => 'EMP002', 'date_hired' => '2015-07-20', 'is_active' => 1, 'height' => 5.6, 'weight' => 140, 'blood_type' => 'A+', 'father_name' => 'Mario Cruz', 'mother_name' => 'Gloria Cruz', 'spouse_name' => null, 'spouse_occupation' => null, 'emergency_contact_person' => 'Roberto Cruz', 'emergency_contact_number' => '09231234567', 'res_brgy' => 'Brgy 2', 'res_city' => 'San Pedro', 'res_prov' => 'Laguna', 'res_region' => 4, 'res_zipcode' => '4023', 'dept_id' => 7, 'college_id' => null, 'created_at' => now(), 'updated_at' => now()],
            ['p_id' => 3, 'patient_id' => 8, 'employee_no' => 'EMP003', 'date_hired' => '2012-09-10', 'is_active' => 1, 'height' => 5.9, 'weight' => 170, 'blood_type' => 'B+', 'father_name' => 'Carlos Ramos', 'mother_name' => 'Veronica Ramos', 'spouse_name' => 'Melissa Ramos', 'spouse_occupation' => 'Teacher', 'emergency_contact_person' => 'Samuel Ramos', 'emergency_contact_number' => '09241234568', 'res_brgy' => 'Brgy 3', 'res_city' => 'Calamba', 'res_prov' => 'Laguna', 'res_region' => 4, 'res_zipcode' => '4027', 'dept_id' => 9, 'college_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['p_id' => 4, 'patient_id' => 9, 'employee_no' => 'EMP004', 'date_hired' => '2018-11-25', 'is_active' => 1, 'height' => 5.5, 'weight' => 130, 'blood_type' => 'AB-', 'father_name' => 'Antonio Aguilar', 'mother_name' => 'Felicia Aguilar', 'spouse_name' => null, 'spouse_occupation' => null, 'emergency_contact_person' => 'Luis Aguilar', 'emergency_contact_number' => '09251234569', 'res_brgy' => 'Brgy 4', 'res_city' => 'Batangas City', 'res_prov' => 'Batangas', 'res_region' => 4, 'res_zipcode' => '4200', 'dept_id' => 12, 'college_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['p_id' => 5, 'patient_id' => 10, 'employee_no' => 'EMP005', 'date_hired' => '2008-03-05', 'is_active' => 1, 'height' => 6.0, 'weight' => 180, 'blood_type' => 'O-', 'father_name' => 'Fernando Lopez', 'mother_name' => 'Marissa Lopez', 'spouse_name' => 'Angela Lopez', 'spouse_occupation' => 'Doctor', 'emergency_contact_person' => 'Sofia Lopez', 'emergency_contact_number' => '09261234570', 'res_brgy' => 'Brgy 5', 'res_city' => 'Santa Rosa', 'res_prov' => 'Laguna', 'res_region' => 4, 'res_zipcode' => '4026', 'dept_id' => 10, 'college_id' => 10, 'created_at' => now(), 'updated_at' => now()],
        ]);        

        DB::table('non_personnel')->insert([
            ['np_id' => 1, 'patient_id' => 11, 'affiliation' => 'Visiting Lecturer', 'created_at' => now(), 'updated_at' => now()],
            ['np_id' => 2, 'patient_id' => 12, 'affiliation' => 'Guest Speaker', 'created_at' => now(), 'updated_at' => now()],
            ['np_id' => 3, 'patient_id' => 13, 'affiliation' => 'Research Collaborator', 'created_at' => now(), 'updated_at' => now()],
            ['np_id' => 4, 'patient_id' => 14, 'affiliation' => 'Industry Consultant', 'created_at' => now(), 'updated_at' => now()],
            ['np_id' => 5, 'patient_id' => 15, 'affiliation' => 'Alumni Association Representative', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
